// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockMessage.proto

package com.itcast.bulls.stock.struct.netty.trade;

public final class StockMessageProto {
  private StockMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KlineData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_KlineData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlaceOrderData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlaceOrderData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlaceOrderResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlaceOrderResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RecallOrderData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RecallOrderData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetOrderData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetOrderData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetOrderResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetOrderResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllPositionData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllPositionData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllPositionList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllPositionList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetFinanceOverviewResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetFinanceOverviewResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAccountSettlementData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAccountSettlementData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAccountSettlementRespData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAccountSettlementRespData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAccountSettlementRespDataList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAccountSettlementRespDataList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022StockMessage.proto\032\017StockHead.proto\032\020S" +
      "tockQuote.proto\"\272\002\n\014StockMessage\022\035\n\tstoc" +
      "kHead\030\001 \001(\0132\n.StockHead\022\037\n\tloginData\030\002 \001" +
      "(\0132\n.LoginDataH\000\022)\n\016placeOrderData\030\003 \001(\013" +
      "2\017.PlaceOrderDataH\000\022\037\n\tklineData\030\004 \001(\0132\n" +
      ".KlineDataH\000\022+\n\017recallOrderData\030\005 \001(\0132\020." +
      "RecallOrderDataH\000\022%\n\014getOrderData\030\006 \001(\0132" +
      "\r.GetOrderDataH\000\022=\n\030getAccountSettlement" +
      "Data\030\007 \001(\0132\031.GetAccountSettlementDataH\000B" +
      "\013\n\tStockData\"S\n\tKlineData\022\017\n\007stockId\030\001 \001" +
      "(\003\022\021\n\tstockCode\030\002 \001(\t\022\021\n\ttimeStart\030\003 \001(\003" +
      "\022\017\n\007timeEnd\030\004 \001(\003\",\n\tLoginData\022\016\n\006userNo" +
      "\030\001 \001(\t\022\017\n\007userPwd\030\002 \001(\t\"\304\003\n\017ResponseMess" +
      "age\022\035\n\tstockHead\030\001 \001(\0132\n.StockHead\022\017\n\007me" +
      "ssage\030\002 \001(\t\022)\n\016placeOrderResp\030\003 \001(\0132\017.Pl" +
      "aceOrderRespH\000\022/\n\021quoteRealtimeResp\030\004 \001(" +
      "\0132\022.QuoteRealtimeRespH\000\0221\n\022klineDataResp" +
      "Lists\030\005 \001(\0132\023.KlineDataRespListsH\000\022%\n\014ge" +
      "tOrderResp\030\006 \001(\0132\r.GetOrderRespH\000\0221\n\022get" +
      "AllPositionList\030\007 \001(\0132\023.GetAllPositionLi" +
      "stH\000\0229\n\026getFinanceOverviewResp\030\010 \001(\0132\027.G" +
      "etFinanceOverviewRespH\000\022M\n getAccountSet" +
      "tlementRespDataList\030\t \001(\0132!.GetAccountSe" +
      "ttlementRespDataListH\000B\016\n\014ResponseData\"i" +
      "\n\016PlaceOrderData\022\017\n\007stockId\030\001 \001(\003\022\021\n\tdir" +
      "ection\030\002 \001(\005\022\014\n\004type\030\003 \001(\005\022\022\n\nexecVolume" +
      "\030\004 \001(\005\022\021\n\texecPrice\030\005 \001(\003\" \n\016PlaceOrderR" +
      "esp\022\016\n\006dealId\030\001 \001(\003\"3\n\017RecallOrderData\022\017" +
      "\n\007orderId\030\001 \001(\003\022\017\n\007stockId\030\002 \001(\003\"\037\n\014GetO" +
      "rderData\022\017\n\007orderId\030\002 \001(\003\"\370\001\n\014GetOrderRe" +
      "sp\022\n\n\002id\030\001 \001(\003\022\021\n\taccountId\030\002 \001(\003\022\017\n\007sto" +
      "ckId\030\003 \001(\003\022\016\n\006status\030\004 \001(\005\022\014\n\004type\030\005 \001(\005" +
      "\022\021\n\tdirection\030\006 \001(\005\022\022\n\ninitVolume\030\007 \001(\005\022" +
      "\022\n\nexecVolume\030\010 \001(\005\022\021\n\texecPrice\030\t \001(\003\022\024" +
      "\n\014requestPrice\030\n \001(\003\022\020\n\010execTime\030\013 \001(\003\022\021" +
      "\n\tstockCode\030\014 \001(\t\022\021\n\tstockName\030\r \001(\t\"\316\002\n" +
      "\022GetAllPositionData\022\n\n\002id\030\001 \001(\003\022\024\n\014trade" +
      "OrderId\030\002 \001(\003\022\021\n\taccountId\030\003 \001(\003\022\017\n\007stoc" +
      "kId\030\004 \001(\003\022\021\n\tcostPrice\030\005 \001(\003\022\016\n\006volume\030\006" +
      " \001(\005\022\023\n\013stockMarket\030\007 \001(\005\022\020\n\010avgPrice\030\010 " +
      "\001(\003\022\027\n\017validSellVolume\030\t \001(\005\022\016\n\006profit\030\n" +
      " \001(\003\022\020\n\010execTime\030\013 \001(\003\022\016\n\006status\030\014 \001(\005\022\020" +
      "\n\010interest\030\r \001(\003\022\021\n\tlastPrice\030\016 \001(\003\022\022\n\np" +
      "rofitRate\030\017 \001(\003\022\021\n\tstockCode\030\020 \001(\t\022\021\n\tst" +
      "ockName\030\021 \001(\t\"E\n\022GetAllPositionList\022/\n\022g" +
      "etAllPositionData\030\001 \003(\0132\023.GetAllPosition" +
      "Data\"\204\001\n\026GetFinanceOverviewResp\022\023\n\013total" +
      "Assets\030\001 \001(\003\022\031\n\021totalMarketAmount\030\002 \001(\003\022" +
      "\026\n\016positionProfit\030\003 \001(\003\022\021\n\tdayProfit\030\004 \001" +
      "(\003\022\017\n\007balance\030\005 \001(\003\">\n\030GetAccountSettlem" +
      "entData\022\021\n\ttimeStart\030\001 \001(\003\022\017\n\007timeEnd\030\002 " +
      "\001(\003\"\276\002\n\034GetAccountSettlementRespData\022\n\n\002" +
      "id\030\001 \001(\003\022\016\n\006userId\030\002 \001(\003\022\016\n\006dealId\030\003 \001(\003" +
      "\022\021\n\taccountId\030\004 \001(\003\022\021\n\ttradeTime\030\005 \001(\003\022\017" +
      "\n\007stockId\030\006 \001(\003\022\021\n\tstockCode\030\007 \001(\t\022\020\n\010cu" +
      "rrency\030\010 \001(\t\022\021\n\tdirection\030\t \001(\005\022\023\n\013trade" +
      "Amount\030\n \001(\003\022\023\n\013tradeVolume\030\013 \001(\003\022\022\n\ntra" +
      "dePrice\030\014 \001(\003\022\r\n\005taxes\030\r \001(\003\022\022\n\ncommissi" +
      "on\030\016 \001(\003\022\016\n\006status\030\017 \001(\005\022\022\n\ncreateTime\030\020" +
      " \001(\003\"g\n GetAccountSettlementRespDataList" +
      "\022C\n\034getAccountSettlementRespData\030\001 \003(\0132\035" +
      ".GetAccountSettlementRespDataB@\n)com.itc" +
      "ast.bulls.stock.struct.netty.tradeB\021Stoc" +
      "kMessageProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.getDescriptor(),
          com.itcast.bulls.stock.struct.netty.trade.StockQuoteProto.getDescriptor(),
        });
    internal_static_StockMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StockMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockMessage_descriptor,
        new java.lang.String[] { "StockHead", "LoginData", "PlaceOrderData", "KlineData", "RecallOrderData", "GetOrderData", "GetAccountSettlementData", "StockData", });
    internal_static_KlineData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_KlineData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_KlineData_descriptor,
        new java.lang.String[] { "StockId", "StockCode", "TimeStart", "TimeEnd", });
    internal_static_LoginData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_LoginData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginData_descriptor,
        new java.lang.String[] { "UserNo", "UserPwd", });
    internal_static_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseMessage_descriptor,
        new java.lang.String[] { "StockHead", "Message", "PlaceOrderResp", "QuoteRealtimeResp", "KlineDataRespLists", "GetOrderResp", "GetAllPositionList", "GetFinanceOverviewResp", "GetAccountSettlementRespDataList", "ResponseData", });
    internal_static_PlaceOrderData_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_PlaceOrderData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlaceOrderData_descriptor,
        new java.lang.String[] { "StockId", "Direction", "Type", "ExecVolume", "ExecPrice", });
    internal_static_PlaceOrderResp_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_PlaceOrderResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlaceOrderResp_descriptor,
        new java.lang.String[] { "DealId", });
    internal_static_RecallOrderData_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_RecallOrderData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RecallOrderData_descriptor,
        new java.lang.String[] { "OrderId", "StockId", });
    internal_static_GetOrderData_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_GetOrderData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetOrderData_descriptor,
        new java.lang.String[] { "OrderId", });
    internal_static_GetOrderResp_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_GetOrderResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetOrderResp_descriptor,
        new java.lang.String[] { "Id", "AccountId", "StockId", "Status", "Type", "Direction", "InitVolume", "ExecVolume", "ExecPrice", "RequestPrice", "ExecTime", "StockCode", "StockName", });
    internal_static_GetAllPositionData_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_GetAllPositionData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllPositionData_descriptor,
        new java.lang.String[] { "Id", "TradeOrderId", "AccountId", "StockId", "CostPrice", "Volume", "StockMarket", "AvgPrice", "ValidSellVolume", "Profit", "ExecTime", "Status", "Interest", "LastPrice", "ProfitRate", "StockCode", "StockName", });
    internal_static_GetAllPositionList_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_GetAllPositionList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllPositionList_descriptor,
        new java.lang.String[] { "GetAllPositionData", });
    internal_static_GetFinanceOverviewResp_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_GetFinanceOverviewResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetFinanceOverviewResp_descriptor,
        new java.lang.String[] { "TotalAssets", "TotalMarketAmount", "PositionProfit", "DayProfit", "Balance", });
    internal_static_GetAccountSettlementData_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_GetAccountSettlementData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAccountSettlementData_descriptor,
        new java.lang.String[] { "TimeStart", "TimeEnd", });
    internal_static_GetAccountSettlementRespData_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_GetAccountSettlementRespData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAccountSettlementRespData_descriptor,
        new java.lang.String[] { "Id", "UserId", "DealId", "AccountId", "TradeTime", "StockId", "StockCode", "Currency", "Direction", "TradeAmount", "TradeVolume", "TradePrice", "Taxes", "Commission", "Status", "CreateTime", });
    internal_static_GetAccountSettlementRespDataList_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_GetAccountSettlementRespDataList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAccountSettlementRespDataList_descriptor,
        new java.lang.String[] { "GetAccountSettlementRespData", });
    com.itcast.bulls.stock.struct.netty.trade.StockHeadProto.getDescriptor();
    com.itcast.bulls.stock.struct.netty.trade.StockQuoteProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
