spring:
  application:
    name: learn-springboot

  # 使用 pom 中定义的属性替换 profiles.active
  profiles:
    active: "@profiles.active@"

  redis:
    host: bigdata01
    port: 6379
    # lettuce 连接池配置（SpringBoot 默认支持的连接池。切换到 Jedis 连接池则需要引入 jedis 依赖）
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 10
        max-wait: 1000ms


  # http client pool 配置
  http-client:
    pool:
      #连接池的最大连接数，0代表不限；如果取0，需要考虑连接泄露导致系统崩溃的后果
      maxTotalConnect: 1000
      #每个路由的最大连接数,如果只调用一个地址,可以将其设置为最大连接数
      maxConnectPerRoute: 200
      # 指客户端和服务器建立连接的超时时间,ms , 最大约21秒,因为内部tcp在进行三次握手建立连接时,默认tcp超时时间是20秒
      connectTimeout: 3000
      # 指客户端从服务器读取数据包的间隔超时时间,不是总读取时间,也就是socket timeout,ms
      readTimeout: 5000
      # 从连接池获取连接的timeout,不宜过大,ms
      connectionRequestTimout: 200
      # 重试次数
      retryTimes: 3
      charset: UTF-8
      # 长连接保持时间 单位s,不宜过长
      keepAliveTime: 10
      keepAliveTargetHost:
        www.baidu.com: 5