spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: sso-client-1
            client-secret: edc45ef0-32ca-434f-a9f9-87ca4f80ca3f
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/client-one/login/oauth2/code/custom
        provider:
          custom:
            authorization-uri: http://localhost:8080/auth/realms/imooc/protocol/openid-connect/auth
            token-uri: http://localhost:8080/auth/realms/imooc/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/auth/realms/imooc/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8080/auth/realms/imooc/protocol/openid-connect/certs}
  thymeleaf:
    cache: false
  cache:
    type: NONE

server:
  port: 8081
  servlet:
    context-path: /client-one

logging:
  level:
    org.springframework: DEBUG