server:
  error:
    whitelabel:
      enabled: true
  port: ${PORT:8080}
  servlet:
    encoding:
      force: true
  forward-headers-strategy: native

spring:
  profiles:
    active: '@spring.profiles.active@'
  cache:
    type: redis
  datasource:
    initialization-mode: embedded
  mail:
    host: ${SMTP_HOST}
    password: ${SMTP_PASSWORD}
    port: ${SMTP_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: ${SMTP_USERNAME}
  messages:
    always-use-message-format: false
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: true
    use-code-as-default-message: false
  mvc:
    throw-exception-if-no-handler-found: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  resources:
    add-mappings: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8080/.well-known/jwks.json}
  session:
    store-type: redis

mooc:
  email-provider:
    api-key: ${EMAIL_API_KEY}
    name: api
  jwt:
    access-token-expire-time: 300000
    header: Authorization
    prefix: 'Bearer '
    refresh-token-expire-time: 2592000000
    key: ${JWT_KEY}
    refresh-key: ${JWT_REFRESH_KEY}
  security:
    role-hierarchy-enabled: true
  sms-provider:
    api-url: ${SMS_API_URL}
    name: ${SMS_PROVIDER_NAME}
  lean-cloud:
    app-id: ${LEAN_CLOUD_APP_ID}
    app-key: ${LEAN_CLOUD_APP_KEY}
  ali:
    api-key: ${ALI_API_KEY}
    api-secret: ${ALI_API_SECRET}