server:
  port: 18082
spring:
  application:
    name: hailtaxi-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用docker启动MySQL数据库：
    # 1. docker run -itd --name mysql-hailtaxi -p 3306:3306 -v /opt/itcast/spring-cloud/data/mysql:/var/lib/mysql -v /opt/itcast/spring-cloud/sql/:/opt/sql -e MYSQL_ROOT_PASSWORD=123456 mysql:8.0
    # 2. docker exec -it mysql-hailtaxi bash
    # 3. 执行sql脚本，导入测试数据
    url: jdbc:mysql://172.16.44.47:3306/hailtaxi-order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: hailtaxi
    password: hailtaxi
  cloud:
    #Consul配置
    consul:
      host: 172.16.44.47
      port: 8500
      discovery:
        #注册到Consul中的服务名字
        service-name: ${spring.application.name}
        #注册的服务的实例 Id，最好不要重复，这里参考官网建议的方式 带随机数
        #instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.i nstance_id:${random.value}}}
        # 自定义实例id为:应用名:ip:port
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        prefer-ip-address: true
        # 开启服务注册
        register: true
        # 开启服务发现
        enabled: true
        # 2分钟之后健康检查未通过取消注册
        health-check-critical-timeout: 2m
        # consul健康检查的轮询周期
        health-check-interval: 10s