server:
  port: 6002
spring:
  application:
    name: seata-bank2
  cloud:
    nacos:
      discovery:
        # Nacos server地址
        server-addr: 192.168.66.100:8848
  datasource:
    url: jdbc:mysql://192.168.66.100:3306/bank2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

seata:
  # 注册中心
  registry:
    type: file
  service:
    # seata服务端的地址和端口信息，多个使用英文分号分隔
    grouplist:
      default: 192.168.66.100:9999
  tx-service-group: my_test_tx_group

logging:
  pattern:
    console: logging.pattern.console=%d{MM/dd HH:mm:ss.SSS} %clr(%-5level) ---  [%-15thread] %cyan(%-50logger{50}):%msg%n