server:
  port: 9000
spring:
  application:
    name: lcn-class-manager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lcn-class?serverTimezone=GMT%2B8
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone:
        - http://localhost:8761/eureka/
# TX-LCN中的transaction client配置信息。 配置TM所在位置。
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070