server:
  servlet:
    context-path: /users
  port: 8000

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/heima_dianping?useSSL=false&serverTimezone=UTC
    username: root
    password: wh001225
    redis:
      host: bigdata01
      port: 6379
      #    password: 001225
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
    jackson:
      default-property-inclusion: non_null # JSON处理时忽略非空字段

mybatis:
  mapper-locations: classpath:mapper/*.xml

