spring:
  security:
    oauth2:
#      client:
#        registration:
#          custom:
#            client-id: sso-client-2
#            client-secret: 9e525cfd-1e3a-44be-ae9b-a828aa2ec7af
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8082/client-two/login/oauth2/code/custom
#        provider:
#          custom:
#            authorization-uri: http://localhost:8080/auth/realms/imooc/protocol/openid-connect/auth
#            token-uri: http://localhost:8080/auth/realms/imooc/protocol/openid-connect/token
#            user-info-uri: http://localhost:8080/auth/realms/imooc/protocol/openid-connect/userinfo
#            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8080/auth/realms/imooc/protocol/openid-connect/certs}
  thymeleaf:
    cache: false
  cache:
    type: NONE

server:
  port: 8082
  servlet:
    context-path: /client-two

logging:
  level:
    org.springframework: DEBUG